In [8]:
import seaborn as sns
import pandas as pd
import numpy as np
import re
import matplotlib.pyplot as plt

from utils import *
from datetime import datetime

In [2]:
raw_df = pd.read_csv('data/FCC_reported_calls.csv')

In [3]:
raw_df.head()

,Ticket ID,Date of Issue,Time of Issue,Form,Method,Issue,Caller ID Number,Type of Call or Messge,Advertiser Business Number,State,Zip,Location (Center point of the Zip Code)
0,100358,01/26/2015,8:35 am,Phone,Wireless (cell phone/other mobile device),Telemarketing (including do not call and spoof...,617-681-5500,Prerecorded Voice,NaN,WA,98115,"WA 98115\n(47.685291, -122.297534)"
1,157640,03/02/2015,2:16 p.m.,Phone,Wired,Telemarketing (including do not call and spoof...,NaN,Prerecorded Voice,NaN,CO,80138,"CO 80138\n(39.518092, -104.688882)"
2,104244,01/28/2015,11:00 AM,Phone,Wireless (cell phone/other mobile device),Robocalls,415-964-2785,Prerecorded Voice,NaN,FL,33139,"FL 33139\n(25.783695, -80.141739)"
3,153519,02/27/2015,11:31 AM,Phone,Wired,Robocalls,404-381-1115,Prerecorded Voice,NaN,VA,22182,"VA 22182\n(38.932908, -77.267432)"
4,145971,02/23/2015,3:24 P.M.,Phone,Wireless (cell phone/other mobile device),Telemarketing (including do not call and spoof...,203-204-2992,Live Voice,NaN,PA,17403,"PA 17403\n(39.935487, -76.710483)"

##### Data cleanup

Columns to remove: Form, Method, Advertiser Business Number, Location, Ticket ID?
Columns to modify: format 'Time of Issue' regex for, 'Method' & 'Issue' remove parenthesis and contents
Remove rows based on NaN on Zip column

In [4]:
# Drop unused columns
fcc_df = raw_df.drop(columns=['Form','Advertiser Business Number','Location (Center point of the Zip Code)'])

# Create a single date+time column
fcc_df['DateTime'] = fcc_df[['Date of Issue','Time of Issue']].apply(lambda row: parse_date(row.values[0],row.values[1]), axis=1)
fcc_df.drop(columns=['Date of Issue','Time of Issue'],inplace=True)

# Split up DateTime column
month, day, year, hour, minute = zip(*[(None, None, None, None, None) if dt is None else (dt.month, dt.day, dt.year, dt.hour, dt.minute) for dt in fcc_df['DateTime']])
fcc_df = fcc_df.assign(Month = month, Day = day, Year = year, Hour = hour, Minute = minute)

# Simply string entries for Method and Issue
fcc_df['Method'] = fcc_df['Method'].apply(func=remove_parenthesis)
fcc_df['Issue'] = fcc_df['Issue'].apply(func=remove_parenthesis)

In [6]:
fcc_df.head()

,Ticket ID,Method,Issue,Caller ID Number,Type of Call or Messge,State,Zip,DateTime,Month,Day,Year,Hour,Minute
0,100358,Wireless,Telemarketing,617-681-5500,Prerecorded Voice,WA,98115,2015-01-26 20:35:00,1,26,2015,20,35
1,157640,Wired,Telemarketing,NaN,Prerecorded Voice,CO,80138,2015-03-02 14:16:00,3,2,2015,14,16
2,104244,Wireless,Robocalls,415-964-2785,Prerecorded Voice,FL,33139,2015-01-28 23:00:00,1,28,2015,23,0
3,153519,Wired,Robocalls,404-381-1115,Prerecorded Voice,VA,22182,2015-02-27 23:31:00,2,27,2015,23,31
4,145971,Wireless,Telemarketing,203-204-2992,Live Voice,PA,17403,2015-02-23 15:24:00,2,23,2015,15,24

In [ ]:
irs_df = pd.read_csv('data/IRS_tax_stats.csv')

In [7]:
irs_df.head()

NameError: name 'irs_df' is not defined